name: FCSDKSample
schemes:
  FCSDKSample:
    build:
      targets:
        FCSDKSample: all
options:
  bundleIdPrefix: uk.co.cerihughes
  deploymentTarget:
    iOS: "16.0"
packages:
  Madog:
    url: https://github.com/cerihughes/Madog
    majorVersion: 7.0.0
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    majorVersion: 5.0.0
targets:
  FCSDKSample:
    type: application
    platform: iOS
    settings:
      INFOPLIST_FILE: FCSDKSample/Info.plist
      DEVELOPMENT_TEAM: Y56955G4Q8
    sources:
      - FCSDKSample
    dependencies:
      - package: Madog
      - package: SnapKit
